"""upgrade store citis

Revision ID: 5a6b66d709cc
Revises: 
Create Date: 2025-10-31 15:15:54.345446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6b66d709cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_cities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('store_cities', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('store_neighborhoods', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('store_neighborhoods', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_neighborhoods', 'longitude')
    op.drop_column('store_neighborhoods', 'latitude')
    op.drop_column('store_cities', 'longitude')
    op.drop_column('store_cities', 'latitude')
    # ### end Alembic commands ###
