"""upgrade store citis

Revision ID: 651babeb3cb6
Revises: 5a6b66d709cc
Create Date: 2025-10-31 19:52:25.833251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651babeb3cb6'
down_revision: Union[str, None] = '5a6b66d709cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_table_activity_created_at', 'table_activity_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_activity_log_created_at'), 'table_activity_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_activity_log_store_id'), 'table_activity_log', ['store_id'], unique=False)
    op.create_index(op.f('ix_table_activity_log_table_id'), 'table_activity_log', ['table_id'], unique=False)
    op.add_column('commands', sa.Column('split_from_command_id', sa.Integer(), nullable=True))
    op.add_column('commands', sa.Column('payment_split_type', sa.String(length=20), nullable=True))
    op.add_column('commands', sa.Column('discount_amount', sa.Integer(), nullable=False))
    op.add_column('commands', sa.Column('service_charge', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'commands', 'commands', ['split_from_command_id'], ['id'], ondelete='SET NULL')
    op.add_column('stores', sa.Column('mercadopago_user_id', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('mercadopago_access_token', sa.LargeBinary(), nullable=True))
    op.add_column('stores', sa.Column('mercadopago_public_key', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('mercadopago_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('mercadopago_last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_stores_mercadopago_user_id'), 'stores', ['mercadopago_user_id'], unique=False)
    op.add_column('tables', sa.Column('assigned_employee_id', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('status_color', sa.String(length=7), nullable=True))
    op.add_column('tables', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('tables', sa.Column('total_orders_today', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('total_revenue_today', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tables_assigned_employee_id'), 'tables', ['assigned_employee_id'], unique=False)
    op.create_foreign_key(None, 'tables', 'users', ['assigned_employee_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('pin_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('pin_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('pin_locked_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_pin_code'), 'users', ['pin_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pin_code'), table_name='users')
    op.drop_column('users', 'pin_locked_until')
    op.drop_column('users', 'pin_attempts')
    op.drop_column('users', 'pin_code')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_index(op.f('ix_tables_assigned_employee_id'), table_name='tables')
    op.drop_column('tables', 'total_revenue_today')
    op.drop_column('tables', 'total_orders_today')
    op.drop_column('tables', 'last_activity_at')
    op.drop_column('tables', 'status_color')
    op.drop_column('tables', 'assigned_employee_id')
    op.drop_index(op.f('ix_stores_mercadopago_user_id'), table_name='stores')
    op.drop_column('stores', 'mercadopago_last_sync_at')
    op.drop_column('stores', 'mercadopago_connected_at')
    op.drop_column('stores', 'mercadopago_public_key')
    op.drop_column('stores', 'mercadopago_access_token')
    op.drop_column('stores', 'mercadopago_user_id')
    op.drop_constraint(None, 'commands', type_='foreignkey')
    op.drop_column('commands', 'service_charge')
    op.drop_column('commands', 'discount_amount')
    op.drop_column('commands', 'payment_split_type')
    op.drop_column('commands', 'split_from_command_id')
    op.drop_index(op.f('ix_table_activity_log_table_id'), table_name='table_activity_log')
    op.drop_index(op.f('ix_table_activity_log_store_id'), table_name='table_activity_log')
    op.drop_index(op.f('ix_table_activity_log_created_at'), table_name='table_activity_log')
    op.drop_index('idx_table_activity_created_at', table_name='table_activity_log')
    op.drop_table('table_activity_log')
    # ### end Alembic commands ###
