"""alter table orders

Revision ID: b2ce234d7a7c
Revises: 14271137dd50
Create Date: 2025-06-27 13:08:18.900377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ce234d7a7c'
down_revision: Union[str, None] = '14271137dd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_id'], ['id'])
    op.drop_constraint('variant_options_store_id_fkey', 'variant_options', type_='foreignkey')
    op.drop_column('variant_options', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_options', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('variant_options_store_id_fkey', 'variant_options', 'stores', ['store_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
